CREATE TABLE USERS (
	USER_ID INTEGER(6) NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(40) NOT NULL,
	LOCATION VARCHAR(30) NOT NULL,
	CARDTYPE VARCHAR(30) NOT NULL,
	CARDNUMBER VARCHAR(30) NOT NULL,
	CVVNUMBER VARCHAR(30) NOT NULL,

PRIMARY KEY (USER_ID)
);
   
CREATE TABLE EXPENSES(
	EXPNSE_ID INTEGER(6) NOT NULL AUTO_INCREMENT,
	ITEMNAME VARCHAR2(100),
	CATEGORY VARCHAR2(20),
	PRICE DECIMAL (4),
	DATE_OF_EXPENSE DATE,

USER_ID INTEGER(6) CONSTRAINT FK_USER_ID REFERENCES USERS);