package com.techleads.app.common;

public interface DBQueries {
	// USER SERVICE QUERIES
	String SELECT_ALL_USER = "SELECT USER_ID, NAME, LOCATION, CARDTYPE, CARDNUMBER, CVVNUMBER FROM USERS";
	String SELECT_USER_BY_ID = "SELECT USER_ID, NAME, LOCATION, CARDTYPE, CARDNUMBER, CVVNUMBER FROM USERS WHERE USER_ID=?";

	String INSERT_INTO_USER = "INSERT INTO USERS (NAME, LOCATION, CARDTYPE, CARDNUMBER, CVVNUMBER) VALUES(?,?,?,?,?)";

	String UPDATE_USER_BY_ID = "UPDATE USERS SET LOCATION=?, CARDTYPE=?, CARDNUMBER=?, CVVNUMBER=? WHERE USER_ID=?";
	String DELETE_USER_BY_ID = "DELETE FROM USERS WHERE USER_ID=?";

	// EXPENSES SERVICE QUERIES
	String INSERT_INTO_EXPENSE = "INSERT INTO EXPENSES(ITEMNAME,CATEGORY,PRICE,DATE_OF_EXPENSE,USER_ID)VALUES(?,?,?,?,?)";

	String SELECT_EXPNS_BY_USER_ID = "SELECT EXPNSE_ID,ITEMNAME,CATEGORY,PRICE,DATE_OF_EXPENSE FROM EXPENSES WHERE USER_ID=?";
}
